import os
import sys
import snapfish2
sys.path.insert(0, os.path.abspath("../.."))
print(sys.path)

# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = "SnapFISH2"
copyright = "2024, Hongyu Yu"
author = "Hongyu Yu"
release = version = snapfish2.__version__

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    "myst_parser",  # markdown files
    "nbsphinx",  # jupyter notebooks
    "sphinx.ext.autodoc",  # auto-documentation
    "sphinx.ext.autosummary",
    "sphinx.ext.intersphinx",  # reference other libraries
    "sphinx.ext.napoleon",  # numpy style
    "sphinx.ext.mathjax",  # math symbols
    "sphinx_design",  # grid card
    "sphinx_tabs.tabs",  # tabs
    "sphinx_copybutton"  # copy button for code chunks
]

source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

myst_enable_extensions = [
    "amsmath",
    "dollarmath",
    "colon_fence"  # sphinx_design
]

# Generate the API documentation when building
autosummary_generate = True

autodoc_member_order = "bysource"
# Set default options for rst generated by autodoc
# "members" -> class rst also shows its methods' documentations
autodoc_default_options = {"members": None, "nosignatures": None}

napoleon_google_docstring = False
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = False
napoleon_use_rtype = True
napoleon_use_param = True
napoleon_custom_sections = [("Params", "Parameters")]
todo_include_todos = False

# Lines starting with the pattern are treated as code
copybutton_prompt_text = r">>> |\$ |... "
copybutton_prompt_is_regexp = True

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "pandas": ("https://pandas.pydata.org/docs/", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "scipy": ("https://docs.scipy.org/doc/scipy/reference/", None),
    "sklearn": ("https://scikit-learn.org/stable/", None),
    "anndata": ("https://anndata.readthedocs.io/en/stable/", None),
    "dask": ("https://docs.dask.org/en/stable/", None)
}

smv_branch_whitelist = r"main"  # Include all branches

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]


# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = "pydata_sphinx_theme"
html_show_sphinx = False
html_show_sourcelink = False

html_theme_options = {
    "logo": {
        "text": "SnapFISH2",
        "alt_text": "SnapFISH2",
    },
    
    "github_url": "https://github.com/hyuhyu104/DNEYET",
    "header_links_before_dropdown": 6,

    "navbar_start": ["navbar-logo", "version-switcher"],
    "navbar_end": ["theme-switcher", "navbar-icon-links"],
    "navbar_align": "left",
}

html_sidebars = {
    "install": [],
    "workflow": [],
}